In [3]:
import pandas as pd
import numpy as np

exp_data = pd.read_csv('exp_dt.csv')
exp_data

,rt,correct,coherent_movement_direction,coherent_orientation,task_type,task_transition,congruency,experiment_type
0,290,False,180,180,mov,NaN,congruent,0
1,471,False,0,180,or,switch,incongruent,0
2,373,False,0,0,or,repetition,congruent,0
3,389,True,0,0,mov,switch,congruent,0
4,632,True,180,0,mov,repetition,incongruent,0
5,459,False,180,180,or,switch,congruent,0
6,691,False,0,180,mov,switch,incongruent,0
7,354,True,180,0,or,switch,incongruent,0
8,332,False,180,0,or,NaN,incongruent,1
9,643,False,180,0,mov,switch,incongruent,1
10,167,True,180,180,or,switch,congruent,1
11,674,True,180,180,mov,switch,congruent,1
12,220,False,0,0,or,switch,congruent,1
13,1877,True,0,180,or,repetition,incongruent,1
14,828,False,0,0,mov,switch,congruent,1
15,248,True,0,180,mov,repetition,incongruent,1
16,542,False,0,0,mov,NaN,congruent,2
17,379,False,180,180,or,switch,congruent,2
18,247,True,180,180,mov,switch,congruent,2
19,202,False,0,180,or,switch,incongruent,2
20,316,False,180,0,or,repetition,incongruent,2
21,273,True,0,180,mov,switch,incongruent,2
22,241,True,180,0,mov,repetition,incongruent,2
23,482,True,0,0,or,switch,congruent,2